/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import authorizeServiceCalls from './rules/authorize-service-calls';

export const configs = {
  recommended,
};

export const rules = {
  'authorize-service-calls': authorizeServiceCalls,
};
